DELIMITER //
CREATE TRIGGER derive_age
AFTER INSERT
ON user FOR EACH ROW
BEGIN
	DECLARE diff INTEGER;
    
    SELECT TIMESTAMPDIFF(YEAR, NEW.dob, CURDATE())
    INTO diff;
    
	SET NEW.age = diff;
END;
DELIMITER ;