DELIMITER //
CREATE TRIGGER derive_age_before_insert
BEFORE INSERT
ON user FOR EACH ROW
BEGIN
	DECLARE diff INTEGER;
    
    SELECT TIMESTAMPDIFF(YEAR, NEW.dob, CURDATE())
    INTO diff;
    
	SET NEW.age = diff;
END//
DELIMITER ;

DELIMITER //
CREATE TRIGGER derive_age_before_update
BEFORE UPDATE
ON user FOR EACH ROW
BEGIN
	DECLARE diff INTEGER;
    
    SELECT TIMESTAMPDIFF(YEAR, NEW.dob, CURDATE())
    INTO diff;
    
	SET NEW.age = diff;
END//
DELIMITER ;